import type { RouteComponent } from 'vue-router';

export const views: Record<
  PageRoute.LastDegreeRouteKey,
  RouteComponent | (() => Promise<{ default: RouteComponent }>)
> = {
  403: () => import('./_builtin/403/index.vue'),
  404: () => import('./_builtin/404/index.vue'),
  500: () => import('./_builtin/500/index.vue'),
  'constant-page': () => import('./_builtin/constant-page/index.vue'),
  login: () => import('./_builtin/login/index.vue'),
  'not-found': () => import('./_builtin/not-found/index.vue'),
  about: () => import('./about/index.vue'),
  'auth-demo_permission': () => import('./auth-demo/permission/index.vue'),
  'auth-demo_super': () => import('./auth-demo/super/index.vue'),
  dashboard_analysis: () => import('./dashboard/analysis/index.vue'),
  dashboard_changePwd: () => import('./dashboard/changePwd/index.vue'),
  dashboard_workbench: () => import('./dashboard/workbench/index.vue'),
  exception_403: () => import('./exception/403/index.vue'),
  exception_404: () => import('./exception/404/index.vue'),
  exception_500: () => import('./exception/500/index.vue'),
  'finance-mg': () => import('./finance-mg/index.vue'),
  'fn-developing_rich-editor-server-developing': () => import('./fn-developing/rich-editor-server-developing/index.vue'),
  'fn_file-upload-server': () => import('./fn/file-upload-server/index.vue'),
  'fn_image-upload-server': () => import('./fn/image-upload-server/index.vue'),
  'fn_rich-editor-server': () => import('./fn/rich-editor-server/index.vue'),
  'fn_tab-detail': () => import('./fn/tab-detail/index.vue'),
  'fn_tab-multi-detail': () => import('./fn/tab-multi-detail/index.vue'),
  fn_tab: () => import('./fn/tab/index.vue'),
  fn_websocket: () => import('./fn/websocket/index.vue'),
  'goods-mg': () => import('./goods-mg/index.vue'),
  management_auth: () => import('./management/auth/index.vue'),
  management_role: () => import('./management/role/index.vue'),
  management_user: () => import('./management/user/index.vue'),
  'multi-menu_first_second-new_third': () => import('./multi-menu/first/second-new/third/index.vue'),
  'multi-menu_first_second': () => import('./multi-menu/first/second/index.vue'),
  'order-mg': () => import('./order-mg/index.vue'),
  plugin_charts_antv: () => import('./plugin/charts/antv/index.vue'),
  plugin_charts_echarts: () => import('./plugin/charts/echarts/index.vue'),
  plugin_copy: () => import('./plugin/copy/index.vue'),
  plugin_editor_markdown: () => import('./plugin/editor/markdown/index.vue'),
  plugin_editor_quill: () => import('./plugin/editor/quill/index.vue'),
  plugin_icon: () => import('./plugin/icon/index.vue'),
  plugin_map: () => import('./plugin/map/index.vue'),
  plugin_print: () => import('./plugin/print/index.vue'),
  plugin_swiper: () => import('./plugin/swiper/index.vue'),
  plugin_video: () => import('./plugin/video/index.vue'),
  productionProcurement: () => import('./productionProcurement/index.vue'),
  test: () => import('./test/index.vue'),
  'user-mg_user-list': () => import('./user-mg/user-list/index.vue'),
  'warehouse-mg': () => import('./warehouse-mg/index.vue')
};
